baseURL = 'https://wisc-rt2.github.io/cs580_fall26/'
languageCode = 'en-us'
title = "CS580 Intelligent Robotics"
theme = "hugo-book"
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true